import "@/app/global.css";
import Providers from "@/redux/provider";
import { Montserrat } from "next/font/google";

const fontMain = Montserrat({
	subsets: ["latin"],
	weight: "variable",
	variable: "--font-main",
});

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${fontMain.variable} bg-primary-300`}>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
